name: Man10ATM
version: ${project.version}
main: red.man10.man10atm.Man10ATM
softdepend: [Man10MySQLAPI,VaultAPI]
depend: [Essentials,Vault]
authors: [Sho0]
description: Man10ATM Plugin
commands:
 atm:
